# Generated by Django 5.1.1 on 2024-10-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(default='使用者名', max_length=50),
        ),
    ]
