# Generated by Django 5.1.1 on 2024-10-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='laboratory',
            field=models.CharField(default='研究室名', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='username',
            field=models.CharField(default='利用者名', max_length=50),
        ),
    ]
